/** Casa host profiles — public-facing host data */
const CASA_HOSTS = {
  'sarah-r': {
    id: 'sarah-r',
    name: 'Sarah R.',
    fullName: 'Sarah Reynolds',
    avatar: 'S',
    avatarClass: '',
    role: 'host',
    verified: true,
    superhost: true,
    location: 'Windermere, Lake District',
    joined: 'March 2023',
    responseRate: 98,
    responseTime: 'within an hour',
    bio: 'Third-generation Cumbrian. I restored Stone Cottage with my partner and love sharing the Lakes with guests who appreciate quiet mornings and proper walks.',
    languages: ['English'],
    propertyIds: [1, 7],
    reviews: 47,
    rating: 4.92,
    listings: 2,
  },
  'patrick-m': {
    id: 'patrick-m',
    name: 'Patrick M.',
    fullName: 'Patrick McAllister',
    avatar: 'P',
    avatarClass: 'ink',
    role: 'host',
    verified: true,
    superhost: false,
    location: 'Bushmills, Causeway Coast',
    joined: 'June 2024',
    responseRate: 95,
    responseTime: 'within 2 hours',
    bio: 'Coastal host on the Causeway Coast. Former B&B owner — I know what guests need before they ask.',
    languages: ['English'],
    propertyIds: [35, 36],
    reviews: 22,
    rating: 4.89,
    listings: 2,
  },
  'emma-t': {
    id: 'emma-t',
    name: 'Emma T.',
    fullName: 'Emma Thorne',
    avatar: 'E',
    avatarClass: 'guest',
    role: 'host',
    verified: true,
    superhost: true,
    location: 'Mousehole, Cornwall',
    joined: 'January 2022',
    responseRate: 100,
    responseTime: 'within 30 minutes',
    bio: 'Cornish born and bred. Harbour Cottage has been in the family for decades — now shared with travellers who love the sea.',
    languages: ['English', 'French'],
    propertyIds: [11, 13],
    reviews: 63,
    rating: 4.95,
    listings: 2,
  },
  'james-h': {
    id: 'james-h',
    name: 'James H.',
    fullName: 'James Harrison',
    avatar: 'J',
    avatarClass: 'guest',
    role: 'guest',
    verified: true,
    superhost: false,
    location: 'London',
    joined: 'September 2025',
    responseRate: null,
    responseTime: null,
    bio: 'Weekend explorer. Always looking for wood burners, good walks, and places that welcome the dog.',
    languages: ['English'],
    propertyIds: [],
    reviews: 8,
    rating: 4.8,
    listings: 0,
  },
  'helen-w': {
    id: 'helen-w',
    name: 'Helen W.',
    fullName: 'Helen Walsh',
    avatar: 'H',
    avatarClass: '',
    role: 'host',
    verified: true,
    superhost: true,
    location: 'Glencoe, Highlands',
    joined: 'November 2021',
    responseRate: 97,
    responseTime: 'within an hour',
    bio: 'Highland bothy keeper and mountain guide. Off-grid hospitality with modern comforts where it counts.',
    languages: ['English', 'Gaelic'],
    propertyIds: [16, 17, 18],
    reviews: 86,
    rating: 4.91,
    listings: 3,
  },
  'david-k': {
    id: 'david-k',
    name: 'David K.',
    fullName: 'David Kerr',
    avatar: 'D',
    avatarClass: 'ink',
    role: 'host',
    verified: true,
    superhost: false,
    location: 'Bourton-on-the-Water, Cotswolds',
    joined: 'April 2024',
    responseRate: 92,
    responseTime: 'within 3 hours',
    bio: 'Cotswolds stone specialist. Restored three properties — each with its own character and a garden worth sitting in.',
    languages: ['English'],
    propertyIds: [27, 29],
    reviews: 75,
    rating: 4.88,
    listings: 2,
  },
};

const CASA_HOST_BY_PROPERTY = {
  1: 'sarah-r', 7: 'sarah-r',
  11: 'emma-t', 13: 'emma-t',
  16: 'helen-w', 17: 'helen-w', 18: 'helen-w',
  27: 'david-k', 29: 'david-k',
  35: 'patrick-m', 36: 'patrick-m',
};

function getCasaHost(hostId) {
  return CASA_HOSTS[hostId] || null;
}

function getCasaHostForProperty(propertyId) {
  const hostId = CASA_HOST_BY_PROPERTY[Number(propertyId)];
  if (hostId) return CASA_HOSTS[hostId];
  const hosts = Object.values(CASA_HOSTS).filter(h => h.role === 'host');
  return hosts[Number(propertyId) % hosts.length];
}

function casaHostProfileUrl(hostId) {
  return `host-profile.html?id=${encodeURIComponent(hostId)}`;
}
